[build]
rustflags = [
    "-C", "link-args=-Wl,-rpath,/Library/Developer/CommandLineTools/Library/Frameworks",
    "-C", "link-args=-L/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib",
]

[env]
PYTHON_SYS_EXECUTABLE = "/usr/bin/python3"
PYO3_PYTHON = "/usr/bin/python3"
